---
title: "Supplementary Material for 'Effects of long-term use of cover crops on weed seedbanks'"
author: "Nichols et al. 2020"
date: "7/15/2020"
header-includes: #allows you to add in your own Latex packages
- \usepackage{float} #use the 'float' package
- \floatplacement{figure}{H}  #make every figure with caption = h, this was the fix
output: 
  pdf_document:
    fig_cap: yes
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(tidyverse)
library(PFIweeds2020)

library(ggridges)
library(scales)
library(ggrepel)
library(patchwork)
library(maps)
library(cowplot)

library(knitr)
library(kableExtra)

```

# General Site Management Summary

```{r gentbl}

pfi_tb <- pfi_sitemgmt %>%
  rename(
    "Site Description" = site_desc, 
    "General Location" = loc,
    "Treatment Description" = trt_desc,
    "Year of Initiation" = initiation_year,
    "Crop Planted in 2019" = crop2019,
    "Number of Treatment Replicates" = reps_nu,
    "Sampled in 2019" = sampled2019,
    "Herbicides Used in 2018 Growing Season" = herb_growingseason2018,
    "Herbicdes Used in Fall 2018" = herb_fall2018,
    "Herbicides Used in Spring 2019" = herb_spring2019,
    "General Herbicide Regime" = herbspring_desc,
    "General Date of Cover Crop Termination" = herbspring2019_date,
    "General Date of Crop Planting" = cropplanting2019_date,
    "Inorganic Fertilizer Used" = inorganic_fert,
    "Organic Fertilizer Used" = organic_fert,
    "Tillage Used" = tillage
    ) 

#--general
pfi_tb %>% 
  select(1:7) %>% 
  kable(caption = "General Site Description", booktabs = T, align = "c") %>% 
  collapse_rows(columns = 1, latex_hline = "major") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  column_spec(column = c(1), width = "5em")  %>% 
  column_spec(column = c(2), width = "5em")  %>% 
  column_spec(column = c(3), width = "5em")  %>% 
  column_spec(column = c(4:6), width = "3em") 
```

\newpage

```{r herbtable}
#--herbicide
pfi_tb %>% 
  select(1, 8:10) %>% 
  kable(caption = "2018-2019 Herbicide Use", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  column_spec(column = c(1:4), width = "8em") %>% 
  collapse_rows(columns = 1, latex_hline = "major")
```

\newpage

```{r mgmttable}

#--mgmt
pfi_tb %>% 
  select(1, 11:16) %>% 
  kable(caption = "General Management", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  column_spec(column = c(2), width = "7em") %>% 
   column_spec(column = c(3:7), width = "5em") %>% 
   collapse_rows(columns = 1, latex_hline = "major")
  
```


\newpage
# Cover crop biomass production over past 10 years of trials

```{r, fig.cap="Winter rye cover crop biomass production at each trial (inset map, more information in Table 1) from 2010-2019 with solid lines representing grain-based maize (Zea mays)-soybean (Glycine max) systems and the dashed line the silage-based system."}

# constant themes ---------------------------------------------------------

mylegendtheme <- theme(legend.position = c(0.01, 0.99),
                       legend.justification = c(0,1),
                       legend.background = element_rect(color = "black"))

myaxistexttheme <- theme(axis.text = element_text(size = rel(1.2)),
                         legend.text = element_text(size = rel(1.2)),
                         axis.title = element_text(size = rel(1.3)),
                         strip.text = element_text(size = rel(1.3)),
                         legend.title = element_text(size = rel(1.3)))


p_green <- "#619B44"
p_blue <- "dodgerblue4"#"#46B2B5"
p_pink <- "#DC1A64"
p_orange <- "#FFA726"
p_yellow <- "#FAE549FD" #"#FFE100"
p_gray <- "#E7E6E6"


# prep work ---------------------------------------------------------------

map_iowa <- as_tibble(map_data('state')) %>%
  filter(region == "iowa")

locs <- pfi_siteinfo %>% 
  unite(site_name, sys_trt, col = "site_sys", remove = F) %>% 
  mutate(site_id = recode(site_sys,
                          "Boyd_grain" = "Central1",
                          "Boyd_silage" = "Central2\n(Silage)",
                          "Funcke_grain" = "West",
                          "Stout_grain" = "East"))


map_iowa <- as_tibble(map_data('state')) %>% 
  filter(region == "iowa")

map_county <- as_tibble(map_data('county')) %>% 
  filter(region == "iowa") 


# map ---------------------------------------------------------------------

fig_map <- 
  ggplot() +
  geom_polygon(data = map_iowa, aes(x = long, y = lat, group = group), 
               color = "black", fill = "white") +
  geom_polygon(data = map_county, aes(x = long, y = lat, group = group), 
               color = "gray80", fill = NA) +
  geom_point(data = locs, aes(lon, lat, fill = county), pch = 21, size = 7, stroke = 2) +
  geom_text(aes(x = -94.9, y = 41.65), size = 5, label = "West (grain)") +
  geom_text(aes(x = -92.5, y = 42.3), size = 5, label = "Central (grain, silage)") +
  geom_text(aes(x = -91.7, y = 41.70), size = 5, label = "East (grain)") +
  theme_minimal()  +
  guides(fill = F) +
  scale_fill_manual(values = c(p_pink, p_yellow, p_blue)) +
  mylegendtheme +
  myaxistexttheme +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) + 
  coord_quickmap() + 
  theme(panel.grid = element_blank())


fig_ccbio <- 
  pfi_ccbio %>% 
  filter(year > 2009) %>% 
  group_by(site_name, sys_trt, year) %>% 
  summarise(mbio = mean(ccbio_Mgha)) %>% 
  ungroup() %>% 
  mutate(site_name = recode(site_name,
                            "Boyd" = "Central",
                            "Funcke" = "West",
                            "Stout" = "East"),
         site_name = factor(site_name, levels = c("West", "Central", "East")),
         sys_trt = str_to_title(sys_trt)) %>% 
  ggplot(aes(year, mbio, color = site_name, 
             group = interaction(site_name, sys_trt))) + 
  geom_line(aes(linetype = sys_trt), size = 2) + 
  scale_x_continuous(breaks = seq(2010, 2018, 2)) +
  scale_color_manual(values = c("Central" = p_pink, 
                                "West" = p_yellow, 
                                "East" = p_blue)) +
  guides(color = F, linetype = F) + 
  labs(linetype = "Cropping System",
       #color = "Site",
       #y = labccbio,
       y = expression(paste("Cover Crop Biomass (Mg  ", ha^-1, ")")),
       x = NULL) + 
  theme_bw() + 
  myaxistexttheme + 
  theme(axis.title.y = element_text(hjust = 0.5, size = rel(1.2)),
        legend.position = "bottom")

ggdraw(fig_ccbio + theme_half_open(12)) +
  draw_plot(fig_map, 0.05, 0.5, .5, .5) 
```



\newpage
# Field wet soil amounts

```{r soilwgtstbl}
pfi_soilwgts %>% 
  kable(caption = "Wet Soil Weights Immediately After Sampling", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  collapse_rows(columns = 1, latex_hline = "major", valign = "top")
```

\newpage
# Statistical Results
 
## Linear models on seedbank density

```{r loo}

m.loo.cont <- read_csv("../01_stats-uni/st_loo.csv")

ggplot(m.loo.cont, aes(site_sys, p.value)) + 
  geom_jitter(width = 0.1, size = 2, aes(color = (loo == 46))) + 
  geom_text_repel(data = m.loo.cont %>%  
                    filter(site_sys == "West_F_grain",
                           loo == 46),
                  label = "outlier") +
  geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
  geom_hline(yintercept = 0.10, linetype = "dashed") + 
  guides(color = F) + 
  labs(title = "Significance of rye vs no-cover comparison when removing single point",
       subtitle = "Removal of outlier changed interpretation of West_F_grain significance")



```



Values are presented for the models run with the full dataset (XX_full) and with the outlier removed (XX_out-rm)

```{r contrasts}
read_csv("../01_stats-uni/st_weedseed-contr-all-models.csv") %>% 
  select(model, site_sys, everything(), -df) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  kable(caption = "Contrasts using full dataset (full) and dataset with outlier removed (out-rm)", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  collapse_rows(columns = c(1), latex_hline = "major", valign = "middle") 
```

```{r estimates}
read_csv("../01_stats-uni/st_weedseed-est-all-models.csv") %>%  
  mutate_if(is.numeric, round, 2) %>% 
  select(model, site_sys, everything(), -df) %>% 
  kable(caption = "Estimates using full dataset (full) and dataset with outlier removed (out-rm)", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  collapse_rows(columns = c(1, 2), latex_hline = "major", valign = "middle") 

```


## Biomass metrics

```{r ccbio10yr}
read_csv("../01_stats-ccbio/sc_ccbio-metrics.csv") %>% 
  mutate_if(is.numeric, round, 2) %>% 
  filter(yr_span == '10yr') %>% 
  select(-yr_span) %>% 
  kable(caption = "Cover crop biomass metrics, 10-year time frame", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  collapse_rows(columns = c(2), latex_hline = "major", valign = "middle")
```

```{r ccbio5yr}
read_csv("../01_stats-ccbio/sc_ccbio-metrics.csv") %>% 
  mutate_if(is.numeric, round, 2) %>% 
  filter(yr_span == '5yr') %>% 
  select(-yr_span) %>% 
  kable(caption = "Cover crop biomass metrics, 5-year time frame", booktabs = T, align = "c") %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), position = "center", full_width = F) %>% 
  collapse_rows(columns = c(2), latex_hline = "major", valign = "middle")
```

```{r, fig.cap="Absolute change in seedbank density vs. cover crop biomass metrics"}
sp_effs <- read_csv("../01_stats-ccbio/sc_ccbio-metrics-effects.csv")
sp_cors <- read_csv("../01_stats-ccbio/sc_ccbio-spear-cors.csv")

sp_effs %>% 
  pivot_longer(cols = c(nabove1:ccbio_2019),
               names_to = 'metric') %>%
  left_join(sp_cors) %>% 
  ggplot(aes(value, -trt_eff_abs)) + 
  geom_point(aes(color = yr_span), size = 2) +
  # #--10yr corrs
  # geom_text(data = . %>% filter(yr_span == "10yr"),
  #           color = "red",
  #           aes(x = 0, y = -4500, label = paste0('corr:', spcor_abs)),
  #           hjust = -1) +
  # #--5yr corrs
  # geom_text(data = . %>% filter(yr_span == "5yr"),
  #           color = "blue4",
  #           aes(x = 0, y = -5000, label = paste0('corr:', spcor_abs)),
  #           hjust = -1) +
  geom_smooth(method = "lm", se = F, aes(color = yr_span)) + 
  scale_color_manual(values = c("10yr" = "red", "5yr" = "blue4")) +
  #coord_cartesian(ylim = c(-5000, 0)) +
  facet_wrap(~metric, scales = "free") + 
  labs(x = NULL,
       y = "Reduction in weed seedbank density\n with use of cover crop (seeds m-2)")
```

```{r, fig.cap = "Relative change in seedbank density vs. cover crop biomass metrics"}
sp_effs %>% 
  pivot_longer(cols = c(nabove1:ccbio_2019),
               names_to = 'metric') %>%
  left_join(sp_cors) %>% 
  ggplot(aes(value, trt_eff_rel)) + 
  geom_point(aes(color = yr_span), size = 2) +
  # #--10yr corrs
  # geom_text(data = . %>% filter(yr_span == "10yr"),
  #           color = "red",
  #           aes(x = 0, y = -4500, label = paste0('corr:', spcor_abs)),
  #           hjust = -1) +
  # #--5yr corrs
  # geom_text(data = . %>% filter(yr_span == "5yr"),
  #           color = "blue4",
  #           aes(x = 0, y = -5000, label = paste0('corr:', spcor_abs)),
  #           hjust = -1) +
  geom_smooth(method = "lm", se = F, aes(color = yr_span)) + 
  scale_color_manual(values = c("10yr" = "red", "5yr" = "blue4")) +
  #coord_cartesian(ylim = c(-5000, 0)) +
  facet_wrap(~metric, scales = "free") + 
  scale_y_continuous(labels = scales::percent_format()) +
  labs(x = NULL,
       y = "Change in weed seedbank density\n with use of cover crop (%)")

```



